name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Check if base debian image changed
        uses: dorny/paths-filter@v2
        id: changes_on_base_docker_image_file
        with:
          filters: |
            src:
              - 'Dockerfile-BaseImage'
      
      - name: Build base image
        if: steps.changes_on_base_docker_image_file.outputs.src == 'true'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/debian -f Dockerfile-BaseImage .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push base image
        if: steps.changes_on_base_docker_image_file.outputs.src == 'true'
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker image tag ${{ secrets.DOCKER_USERNAME }}/debian ${{ secrets.DOCKER_USERNAME }}/debian:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/debian:$IMAGE_TAG
          docker image tag ${{ secrets.DOCKER_USERNAME}}/debian ${{ secrets.DOCKER_USERNAME }}/debian:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/debian:latest

      - name: Build docker image of server
        run: docker build -t server .

      - name: Build, tag, and push docker image to Docker Hub 
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker image tag server ${{ secrets.DOCKER_USERNAME }}/server:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME}}/server:$IMAGE_TAG
          docker image tag server ${{ secrets.DOCKER_USERNAME }}/server:latest
          docker push ${{ secrets.DOCKER_USERNAME}}/server:latest

